/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorConsumo;
import Controlador.ControladorReportes;
import Modelo.Consumo_Cliente;
import Vista.Clases.FuncionesGenerales;
import Vista.Clases.ManejadorComponentes;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import Vista.Clases.MenuBoton;
import Vista.Clases.TablaPersonalizada;
import static Vista.Clases.TablaSpinnerPersonalizada.llenarTabla2columnas;
import java.awt.BorderLayout;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author TomasPC
 */
public class JF_Reportes extends javax.swing.JFrame {
    private MenuBoton menu;
    private ControladorReportes reportes = new ControladorReportes();
    private ControladorConsumo cliente = new ControladorConsumo();
    private ManejadorComponentes manejadorComponentes = new ManejadorComponentes();
    FuncionesGenerales funcionesGenerales = new FuncionesGenerales();
    private java.util.List<String[]> notificaciones;
    /**
     * Creates new form JF_Reportes
     * @param Name
     * @param notificaciones
     */
    public JF_Reportes(String Name, java.util.List<String[]> notificaciones) {
        initComponents();
        lblErrorFecha.setVisible(false);
        lblErrorFechaF.setVisible(false);
        this.notificaciones = notificaciones;
        jLabel2.setText(Name);
        menu = new MenuBoton(300, getContentPane().getHeight() - 185, this, notificaciones);
        reportes.ReporteMinimos();
        reportes.ReporteProductosEstancados();
        customComponents(Name);
        eventComponents();
        this.setExtendedState(JF_Reportes.MAXIMIZED_BOTH);
    }
    private void customComponents(String Name){
        hideshowLabelsbuttons(false);
        
        menu.setButtonIcon(jButton1, "/Imagenes/IconoMenu.png");
        menu.setButtonIcon(jButton2, "/Imagenes/IconoRegresar.png");

        TablaPersonalizada.setScrollPaneProperties(jScrollPane1);
        DefaultTableModel model = llenarTabla2columnas(llamarReporte(Name));
        TablaPersonalizada.setTableProperties(Reportes, model, false);

        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(jScrollPane2, BorderLayout.CENTER);
        manejadorComponentes.agregarLabel(lblErrorFecha);
        manejadorComponentes.agregarLabel(lblErrorFechaF);
        manejadorComponentes.agregarText(txtFechaFinal);
        manejadorComponentes.agregarText(txtFechaFinal);
        pack();
        
    }
    private void eventComponents() {
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (menu.menuAbierto) {
                    menu.cerrarMenu();
                } else {
                    menu.mostrarMenu();
                }
            }
        });
    }
    
    private void hideshowLabelsbuttons(boolean opcion){
        FechaInicio.setVisible(opcion);
        FechaFinal.setVisible(opcion);
        txtFechaFinal.setVisible(opcion);
        txtFechaInicio.setVisible(opcion);
        Buscar.setVisible(opcion);
        MontoTotal.setVisible(opcion);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        FechaInicio = new javax.swing.JLabel();
        FechaFinal = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        txtFechaFinal = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        lblErrorFechaF = new javax.swing.JLabel();
        lblErrorFecha = new javax.swing.JLabel();
        MontoTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Reportes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1747, 1291));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(1747, 1291));
        jPanel4.setMinimumSize(new java.awt.Dimension(1747, 1291));
        jPanel4.setPreferredSize(new java.awt.Dimension(775, 484));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(152, 194, 70));

        jLabel1.setFont(new Font("Montserrat", Font.BOLD, 40));
        jLabel1.setForeground(new java.awt.Color(25, 25, 25));
        jLabel1.setText("Cotos Food");

        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setMaximumSize(new java.awt.Dimension(71, 78));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1404, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1747, -1));

        jButton2.setToolTipText("");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDefaultCapable(false);
        jButton2.setMaximumSize(new java.awt.Dimension(71, 78));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 131, 71, 78));

        jLabel2.setFont(new Font("Montserrat", Font.BOLD, 64));
        jLabel2.setForeground(new java.awt.Color(25, 25, 25));
        jLabel2.setText("Consumo Empleados");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jPanel3.setBackground(new java.awt.Color(152, 194, 70));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 122));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 1230, 60));

        FechaInicio.setFont(new Font("Montserrat", Font.BOLD, 24));
        FechaInicio.setText("Fecha Inicio:");
        jPanel4.add(FechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 930, -1, -1));

        FechaFinal.setFont(new Font("Montserrat", Font.BOLD, 24));
        FechaFinal.setText("Fecha Final:");
        jPanel4.add(FechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 930, -1, -1));

        Buscar.setBackground(new java.awt.Color(0, 72, 121));
        Buscar.setFont(new Font("Montserrat", Font.BOLD, 24));
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel4.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 910, 199, 50));

        txtFechaFinal.setFont(new Font ("Montserrat", Font.PLAIN,26));
        jPanel4.add(txtFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 920, 210, 40));

        txtFechaInicio.setFont(new Font ("Montserrat", Font.PLAIN,26));
        jPanel4.add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 920, 210, 40));

        lblErrorFechaF.setForeground(new java.awt.Color(194, 8, 8));
        lblErrorFechaF.setText("La fecha debe de seguir el formato dd/mm/aaaa");
        jPanel4.add(lblErrorFechaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 960, 290, 30));

        lblErrorFecha.setForeground(new java.awt.Color(194, 8, 8));
        lblErrorFecha.setText("La fecha debe de seguir el formato dd/mm/aaaa");
        jPanel4.add(lblErrorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 960, 290, 30));

        MontoTotal.setFont(new Font("Montserrat", Font.BOLD, 24));
        MontoTotal.setText("Total:");
        jPanel4.add(MontoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 930, -1, -1));

        Reportes.setFont(new Font ("Montserrat", Font.PLAIN,20));
        Reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Columna1", "Columna2"
            }
        ));
        jScrollPane1.setViewportView(Reportes);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 1230, 450));

        jScrollPane2.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1832, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new JF_Principal(notificaciones).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        List<Consumo_Cliente> consumo = null;
        List<String[]> datos = null;
        if (!txtFechaInicio.getText().isEmpty() && !txtFechaFinal.getText().isEmpty()){
            if (funcionesGenerales.validarFecha(txtFechaInicio.getText(), 0, manejadorComponentes) && funcionesGenerales.validarFecha(txtFechaFinal.getText(), 1, manejadorComponentes)){
                try {
                    consumo = reportes.ReporteVentas(dateFormat.parse(txtFechaInicio.getText()), dateFormat.parse(txtFechaFinal.getText()));
                } catch (ParseException ex) {
                    Logger.getLogger(JF_Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else{
            consumo = reportes.ReporteVentas(Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant()), Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant()));
        }
        
        datos = cliente.LlenarTablaClientes(consumo);
        DefaultTableModel model = llenarTabla2columnas(datos);
        MontoTotal.setText("Monto Total: "+ rellenarTotal(consumo));
        TablaPersonalizada.setTableProperties(Reportes, model, false);
        
    }//GEN-LAST:event_BuscarActionPerformed
    private double rellenarTotal(List<Consumo_Cliente> clientes){
        double result = 0;
        for (Consumo_Cliente c: clientes){
            result += c.getMonto();
        }
        return result;
    }
    private List<String[]> llamarReporte(String Name){
        List<String[]> datos = new ArrayList<>();
        switch(Name){
            case "Reporte de ventas" -> {hideshowLabelsbuttons(true);break;}
            case "Reporte de costo de mercadería más vendida" -> {datos = reportes.LlenarTablaMenu(reportes.ReporteCostoMasVendidos(), 1); break;}
            case "Reporte de productos estancados" -> {datos = reportes.LlenarTablaMenu(reportes.ReporteProductosEstancados(), 0); break;}
            case "Reporte de cantidad de productos mínimos" -> {datos = reportes.LlenarTablaProductos(reportes.ReporteMinimos()); break;}
            default -> {break;}
        }
        return datos;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Reportes(args[0], null).setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel FechaFinal;
    private javax.swing.JLabel FechaInicio;
    private javax.swing.JLabel MontoTotal;
    private javax.swing.JTable Reportes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErrorFecha;
    private javax.swing.JLabel lblErrorFechaF;
    private javax.swing.JTextField txtFechaFinal;
    private javax.swing.JTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
}
